theme: jekyll-theme-minimal
title: Yesith Alexander Alvarez Matta
logo: "/images/banner.jpg"
description: Certified Profesional, Red Team Lead, Pentester, Ethical Hacker, expert in systems infiltration, information leakage and cyber warfare techniques, passionate about offensive security, digital forensic techniques and the detection of malware. Thirteen years on the banking sector have provided the experience and training to protect the confidentiality, integrity and availability of large systems.
