title: Eng. Yesith Alvarez
logo: /assets/img/banner.jpg
description: Certified Profesional, Red Team Lead, Pentester, Ethical Hacker, expert in systems infiltration, information leakage and cyber warfare techniques, passionate about offensive security, digital forensic techniques and the detection of malware. Thirteen years on the banking sector have provided the experience and training to protect the confidentiality, integrity and availability of large systems.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
